services:
  # 1. MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto
    container_name: pm_mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 2. Time Series Database (InfluxDB)
  influxdb:
    image: influxdb:2.7
    container_name: pm_influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=engineer_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Maintenance*2026*
      - DOCKER_INFLUXDB_INIT_ORG=Company_Asset_Mgmt
      - DOCKER_INFLUXDB_INIT_BUCKET=vibration_stream

  # 3. Visualization (Grafana)
  grafana:
    image: grafana/grafana
    container_name: pm_grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
